export type ValidatorType = {
    voteId: string;
    validatorId: string;
    apy: number | null;
    apyEst: number | null;
    apyComparedMax: number | null;
    fee: number | null;
    totalStake: string | null;
    network: string | null;
    name: string | null;
    details: string | null;
    website: string | null;
    keybaseUsername?: any | null;
    iconUrl: string | null;
    inTop33: boolean | null;
    isDelinquent: boolean | null;
    inJpool: boolean | null;
    jpoolLamports: string | null;
    svName: string | null;
    lastVote: string | null;
    nodeVersion: string | null;
    epoch: number | null;
    inactive: boolean | null;
    vaScore: number | null;
    vaRootDist: number | null;
    vaVoteDist: number | null;
    vaSoftware: number | null;
    vaPublishedInfo: number | null;
    vaSkippedSlot: number | null;
    vaSecurityReport: number | null;
    vaConsensusMods: number | null;
    vaWithdrawer: number | null;
    vaDataCenter: number | null;
    vaStakeConcentration: number | null;
  }